rvm:
  - 2.1
  - 2.2.2
  - 2.3.4

script: "bundle exec rake clean spec cucumber"

before_install:
  - gem install bundler -v '~> 1.10'

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/5.0.gemfile
      rvm: 2.1

sudo: false
cache: bundler
